// <auto-generated />
namespace Runas_Explosivas.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-beta1-60406")]
    public sealed partial class ProductoModificada : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProductoModificada));
        
        string IMigrationMetadata.Id
        {
            get { return "201708040735519_ProductoModificada"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
